var state = {
	"uiState": {
		"chordMode" : false,
			"chordToPaint" : "E",
			"paintSpecificity" : "text",
			"focus" : undefined,
			"editModal" : {
				"showEditModal" : false,
				"editableText" : "",
				"editableTextKey" : ""
			}
	},
	"song": {
		"title" : "I Feel Fine",
		"author" : "Lennon and McCartney",
		"structure" : [
			{
				"sectionName" : "Verse",
				"lines" : [
					{
						"fullLine" : "Baby's good to me",
						"characters" : [
							{"character" : "B", "chord" : "G"},
							{"character" : "a", "chord" : "G"},
							{"character" : "b", "chord" : "G"},
							{"character" : "y", "chord" : "G"},							
							{"character" : "'", "chord" : "G"},
							{"character" : "s", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "g", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "d", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "t", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : " ", "chord" : "G"},							
							{"character" : "m", "chord" : "G"},
							{"character" : "e", "chord" : "G"}
						]
					}, {
						"fullLine" : "You know she's happy as can be",
						"characters" : [
							{"character" : "Y", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "u", "chord" : "G"},
							{"character" : " ", "chord" : "G"},							
							{"character" : "k", "chord" : "G"},
							{"character" : "n", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "w", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "s", "chord" : "G"},
							{"character" : "h", "chord" : "G"},
							{"character" : "e", "chord" : "G"},
							{"character" : "'", "chord" : "G"},
							{"character" : "s", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "h", "chord" : "G"},							
							{"character" : "a", "chord" : "G"},
							{"character" : "p", "chord" : "G"},
							{"character" : "p", "chord" : "G"},
							{"character" : "y", "chord" : "G"},							
							{"character" : " ", "chord" : "G"},
							{"character" : "a", "chord" : "G"},
							{"character" : "s", "chord" : "G"},							
							{"character" : " ", "chord" : "G"},
							{"character" : "c", "chord" : "G"},
							{"character" : "a", "chord" : "G"},
							{"character" : "n", "chord" : "G"},							
							{"character" : " ", "chord" : "G"},
							{"character" : "b", "chord" : "G"},
							{"character" : "e", "chord" : "G"}
						]
					}, {
						"fullLine" : "You know she said so",
						"characters" : [
							{"character" : "Y", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "u", "chord" : "G"},
							{"character" : " ", "chord" : "G"},							
							{"character" : "k", "chord" : "G"},
							{"character" : "n", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "w", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "s", "chord" : "G"},
							{"character" : "h", "chord" : "G"},
							{"character" : "e", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "s", "chord" : "D"},
							{"character" : "a", "chord" : "D"},
							{"character" : "i", "chord" : "D"},							
							{"character" : "d", "chord" : "D"},
							{"character" : " ", "chord" : "D"},
							{"character" : "s", "chord" : "D"},
							{"character" : "o", "chord" : "D"}					
						]
					}, {
						"fullLine" : "I'm in love with her and I feel fine",
						"characters" : [
							{"character" : "I", "chord" : "D"},
							{"character" : "'", "chord" : "D"},
							{"character" : "m", "chord" : "D"},
							{"character" : " ", "chord" : "D"},
							{"character" : "i", "chord" : "D"},
							{"character" : "n", "chord" : "D"},
							{"character" : " ", "chord" : "D"},
							{"character" : "l", "chord" : "D"},
							{"character" : "o", "chord" : "D"},
							{"character" : "v", "chord" : "D"},
							{"character" : "e", "chord" : "D"},
							{"character" : " ", "chord" : "D"},
							{"character" : "w", "chord" : "D"},
							{"character" : "i", "chord" : "D"},
							{"character" : "t", "chord" : "D"},
							{"character" : "h", "chord" : "D"},
							{"character" : " ", "chord" : "D"},
							{"character" : "h", "chord" : "C"},
							{"character" : "e", "chord" : "C"},
							{"character" : "r", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "a", "chord" : "C"},
							{"character" : "n", "chord" : "C"},
							{"character" : "d", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "I", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "f", "chord" : "C"},
							{"character" : "e", "chord" : "C"},
							{"character" : "e", "chord" : "C"},
							{"character" : "l", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "f", "chord" : "G"},
							{"character" : "i", "chord" : "G"},
							{"character" : "n", "chord" : "G"},
							{"character" : "e", "chord" : "G"}
						]
					}
				]
			}, {
				"sectionName" : "Middle Eight",
				"lines" : [
					{
						"fullLine" : "I'm so glad that she's my little girl",
						"characters" : [
							{"character" : "I", "chord" : "G"},
							{"character" : "'", "chord" : "G"},
							{"character" : "m", "chord" : "G"},
							{"character" : " ", "chord" : "G"},							
							{"character" : "s", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "g", "chord" : "Bm"},
							{"character" : "l", "chord" : "Bm"},
							{"character" : "a", "chord" : "Bm"},
							{"character" : "d", "chord" : "Bm"},
							{"character" : " ", "chord" : "Bm"},
							{"character" : "t", "chord" : "Bm"},
							{"character" : "h", "chord" : "Bm"},
							{"character" : "a", "chord" : "Bm"},							
							{"character" : "t", "chord" : "Bm"},
							{"character" : " ", "chord" : "Bm"},
							{"character" : "s", "chord" : "C"},
							{"character" : "h", "chord" : "C"},
							{"character" : "e", "chord" : "C"},
							{"character" : "'", "chord" : "C"},							
							{"character" : "s", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "m", "chord" : "C"},
							{"character" : "y", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "l", "chord" : "C"},
							{"character" : "i", "chord" : "C"},
							{"character" : "t", "chord" : "C"},
							{"character" : "t", "chord" : "C"},
							{"character" : "l", "chord" : "C"},							
							{"character" : "e", "chord" : "C"},
							{"character" : " ", "chord" : "C"},
							{"character" : "g", "chord" : "G"},
							{"character" : "i", "chord" : "G"},
							{"character" : "r", "chord" : "G"},
							{"character" : "l", "chord" : "G"}
						]
					}, {
						"fullLine" : "She's so glad she's telling all the world",
						"characters" : [
							{"character" : "S", "chord" : "G"},
							{"character" : "h", "chord" : "G"},
							{"character" : "e", "chord" : "G"},
							{"character" : "'", "chord" : "G"},							
							{"character" : "s", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "s", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : " ", "chord" : "G"},
							{"character" : "g", "chord" : "Bm"},
							{"character" : "l", "chord" : "Bm"},
							{"character" : "a", "chord" : "Bm"},
							{"character" : "d", "chord" : "Bm"},
							{"character" : " ", "chord" : "Bm"},
							{"character" : "s", "chord" : "Bm"},							
							{"character" : "h", "chord" : "Bm"},
							{"character" : "e", "chord" : "Bm"},
							{"character" : "'", "chord" : "Bm"},
							{"character" : "s", "chord" : "Bm"},
							{"character" : " ", "chord" : "Bm"},
							{"character" : "t", "chord" : "Am"},							
							{"character" : "e", "chord" : "Am"},
							{"character" : "l", "chord" : "Am"},
							{"character" : "l", "chord" : "Am"},
							{"character" : "i", "chord" : "Am"},
							{"character" : "n", "chord" : "Am"},
							{"character" : "g", "chord" : "Am"},
							{"character" : " ", "chord" : "Am"},
							{"character" : "a", "chord" : "Am"},
							{"character" : "l", "chord" : "Am"},
							{"character" : "l", "chord" : "Am"},
							{"character" : " ", "chord" : "Am"},							
							{"character" : "t", "chord" : "Am"},
							{"character" : "h", "chord" : "Am"},
							{"character" : "e", "chord" : "Am"},
							{"character" : " ", "chord" : "Am"},
							{"character" : "w", "chord" : "G"},
							{"character" : "o", "chord" : "G"},
							{"character" : "r", "chord" : "G"},
							{"character" : "l", "chord" : "G"},
							{"character" : "d", "chord" : "G"}
						]
					}
				]
			}
		]
	}
};